# Generated by Django 5.2.3 on 2025-06-17 07:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Student Full Name')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Student Email')),
                ('semester', models.CharField(blank=True, choices=[('SEM_ONE', 'Semester One'), ('SEM_TWO', 'Semester Two'), ('SEM_THREE', 'Semester Three'), ('SEM_FOUR', 'Semester Four'), ('SEM_FIVE', 'Semester Five'), ('SEM_SIX', 'Semester Six'), ('SEM_SEVEN', 'Semester Seven'), ('SEM_EIGHT', 'Semester Eight')], default='N/A', max_length=20, null=True)),
                ('phone_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Teacher Full Name')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Teacher Email')),
                ('department', models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical Engineering'), ('IT', 'Information Technology')], default='N/A', max_length=5, null=True)),
                ('phone_number', models.IntegerField()),
                ('join_date', models.DateField(default='JOIN_DATE')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Material Title')),
                ('category', models.CharField(choices=[('SLIDE', 'Chapter Slide'), ('TEXT_BOOK', 'A Text Book'), ('REFERENCE_BOOK', 'A Reference Book'), ('AUDIO', 'Audio Material')], max_length=20, verbose_name='Material Category')),
                ('description', models.CharField(max_length=500, verbose_name='Material Description')),
                ('SUBJECT', models.CharField(choices=[('BCT001', 'Software Engineering'), ('BCT002', 'Database Management System'), ('BCT003', 'Computer Networks'), ('BCT004', 'Operating System'), ('BCT005', 'Data Structures and Algorithms'), ('BCT006', 'Object Oriented Programming'), ('BCT007', 'Web Technologies'), ('BCT008', 'Mobile Application Development')], default='N/A', max_length=20, verbose_name='Subject')),
                ('file', models.FileField(upload_to='material/', verbose_name='Material File Name')),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2025, 6, 17, 13, 42, 6, 312600), verbose_name='Upload Date')),
                ('teacher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Assignment Title')),
                ('start_date', models.DateField(default='N/A', verbose_name='Start Date')),
                ('due_date', models.DateField(default='N/A', verbose_name='Due Date')),
                ('question_file', models.FileField(blank=True, null=True, upload_to='assignments/questions', verbose_name='Select Assignment File')),
                ('remark', models.CharField(max_length=100, verbose_name='Assignment Remark')),
                ('full_mark', models.FloatField()),
                ('SUBJECT', models.CharField(choices=[('BCT001', 'Software Engineering'), ('BCT002', 'Database Management System'), ('BCT003', 'Computer Networks'), ('BCT004', 'Operating System'), ('BCT005', 'Data Structures and Algorithms'), ('BCT006', 'Object Oriented Programming'), ('BCT007', 'Web Technologies'), ('BCT008', 'Mobile Application Development')], default='N/A', max_length=20, verbose_name='Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-title'],
            },
        ),
    ]
