# Generated by Django 5.2.3 on 2025-06-15 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Assignment Title')),
                ('start_date', models.DateField(default='N/A', verbose_name='Start Date')),
                ('due_date', models.DateField(default='N/A', verbose_name='Due Date')),
                ('question_file', models.FileField(blank=True, null=True, upload_to='assignments/questions', verbose_name='Select Assignment File')),
                ('remark', models.CharField(max_length=100, verbose_name='Assignment Remark')),
                ('full_mark', models.FloatField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-title'],
            },
        ),
    ]
